// CardSinMapGen — build-time code generator.
// Reads assets/overrides/cards/*.json and emits a static Dictionary<string, Sin> in C#.
// Called by TheCity.csproj's BeforeCompile target.
//
// Usage: CardSinMapGen <json_dir> <output_cs>

using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

if (args.Length < 2)
{
    Console.Error.WriteLine("Usage: CardSinMapGen <json_dir> <output_cs>");
    return 1;
}

string jsonDir = args[0];
string outPath = args[1];

if (!Directory.Exists(jsonDir))
{
    Console.Error.WriteLine($"[CardSinMapGen] ERROR: directory not found: {jsonDir}");
    return 1;
}

// Sin ordinal ↔ name (matches src/Resource/Sin.cs).
string[] SinNames = { "Wrath", "Lust", "Sloth", "Gluttony", "Gloom", "Pride", "Envy" };

var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
var files = Directory.GetFiles(jsonDir, "*.json").OrderBy(f => f, StringComparer.Ordinal).ToList();
var rows = new List<(string Id, string SinName, string Source)>();

foreach (var file in files)
{
    CardOverride? card;
    try
    {
        card = JsonSerializer.Deserialize<CardOverride>(File.ReadAllText(file), opts);
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"[CardSinMapGen] ERROR parsing {file}: {ex.Message}");
        return 1;
    }
    if (card == null || string.IsNullOrWhiteSpace(card.CardId))
    {
        Console.Error.WriteLine($"[CardSinMapGen] ERROR: {file} missing cardId");
        return 1;
    }

    int sinOrdinal;
    string source;
    if (card.Sin is int s)
    {
        if (s < 0 || s >= SinNames.Length)
        {
            Console.Error.WriteLine($"[CardSinMapGen] ERROR: {card.CardId} sin={s} out of range 0..{SinNames.Length - 1}");
            return 1;
        }
        sinOrdinal = s;
        source = "file";
    }
    else
    {
        // Deterministic fallback: FNV-1a(cardId) % 7
        sinOrdinal = (int)(StableHash(card.CardId!) % (uint)SinNames.Length);
        source = "hash";
    }

    rows.Add((card.CardId!, SinNames[sinOrdinal], source));
}

// Emit .g.cs
var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine($"// Source: {files.Count} JSON files in '{Path.GetFileName(jsonDir)}/' — DO NOT EDIT THIS FILE.");
sb.AppendLine($"// Regenerate by editing JSONs and running 'dotnet build'.");
sb.AppendLine("#nullable enable");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine();
sb.AppendLine("namespace TheCity.Resource;");
sb.AppendLine();
sb.AppendLine("public static class CardSinMap");
sb.AppendLine("{");
sb.AppendLine($"    /// <summary>{rows.Count} entries — built from assets/overrides/cards/*.json</summary>");
sb.AppendLine($"    public static readonly IReadOnlyDictionary<string, Sin> ById =");
sb.AppendLine($"        new Dictionary<string, Sin>({rows.Count})");
sb.AppendLine("        {");
foreach (var (id, sin, _) in rows)
{
    sb.AppendLine($"            {{ \"{Escape(id)}\", Sin.{sin} }},");
}
sb.AppendLine("        };");
sb.AppendLine("}");

var newContent = sb.ToString();

// Incremental: skip write if identical (preserves mtime, avoids needless recompile).
if (File.Exists(outPath))
{
    var existing = File.ReadAllText(outPath);
    if (existing == newContent)
    {
        Console.WriteLine($"[CardSinMapGen] Up-to-date ({rows.Count} entries), skip write.");
        return 0;
    }
}

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, newContent);

int fromFile = rows.Count(r => r.Source == "file");
int fromHash = rows.Count(r => r.Source == "hash");
Console.WriteLine($"[CardSinMapGen] Wrote {rows.Count} entries ({fromFile} explicit, {fromHash} hash-fallback) → {outPath}");
return 0;

// ── helpers ──

static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

// FNV-1a 32-bit. Stable across .NET versions unlike string.GetHashCode.
static uint StableHash(string s)
{
    uint hash = 2166136261u;
    foreach (char c in s)
    {
        hash ^= c;
        hash *= 16777619u;
    }
    return hash;
}

sealed class CardOverride
{
    [JsonPropertyName("cardId")] public string? CardId { get; set; }
    [JsonPropertyName("sin")]    public int?    Sin    { get; set; }
    // Other fields (cardType, rarity, etc.) ignored — generator only needs cardId + sin.
}
